"""empty message

Revision ID: 005befa404c4
Revises: c5d436b01a53
Create Date: 2020-12-19 15:43:11.974785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005befa404c4'
down_revision = 'c5d436b01a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('downloads', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('downloads')

    # ### end Alembic commands ###
