"""empty message

Revision ID: 185956677e05
Revises: 005befa404c4
Create Date: 2020-12-19 17:26:26.035601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '185956677e05'
down_revision = '005befa404c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
